import mjml2html from 'mjml';

/**
 * Wraps the AI-generated content in a minimalist MJML template and returns the HTML.
 * @param content The HTML content generated by the AI (e.g., news summary).
 * @returns The compiled HTML email ready for sending.
 */
export function generateMjmlEmail(content: string): string {
  const mjmlTemplate = `
    <mjml>
      <mj-head>
        <mj-attributes>
          <mj-all font-family="Helvetica, Arial, sans-serif" />
          <mj-text font-size="16px" color="#333333" line-height="1.6" />
          <mj-section padding="20px 0" />
        </mj-attributes>
        <mj-style>
          h1 { font-size: 24px; font-weight: bold; margin-bottom: 20px; color: #1a1a1a; }
          h2 { font-size: 20px; font-weight: bold; margin-top: 24px; margin-bottom: 12px; color: #1a1a1a; }
          h3 { font-size: 18px; font-weight: bold; margin-top: 20px; margin-bottom: 10px; color: #1a1a1a; }
          p { margin-bottom: 16px; }
          a { color: #0066cc; text-decoration: none; }
          ul { margin-bottom: 16px; padding-left: 20px; }
          li { margin-bottom: 8px; }
        </mj-style>
      </mj-head>
      <mj-body background-color="#f4f4f4">
        <mj-section padding="20px">
          <mj-column>
          </mj-column>
        </mj-section>
        
        <mj-section background-color="#ffffff" border-radius="8px" padding="40px 20px" padding-bottom="20px">
          <mj-column>
            <mj-text>
              ${content}
            </mj-text>
          </mj-column>
        </mj-section>

        <mj-section padding="20px">
          <mj-column>
            <mj-text align="center" font-size="12px" color="#888888">
              &copy; ${new Date().getFullYear()} News Agentic. Todos os direitos reservados.
            </mj-text>
          </mj-column>
        </mj-section>
      </mj-body>
    </mjml>
  `;

  const { html, errors } = mjml2html(mjmlTemplate);

  if (errors && errors.length > 0) {
    console.error('Erros na compilação do MJML:', errors);
    // Em caso de erro crítico, poderíamos lançar uma exceção,
    // mas retorna o HTML gerado (que pode estar incompleto) ou o próprio conteúdo como fallback se falhar totalmente
    // mas geralmente mjml2html retorna algo mesmo com erros leves.
  }

  return html;
}
